#!/usr/bin/env python3
"""Write population_sets.yaml (bash-pipeline format: top-level `Populations:`)
and results/variant_qc/hybrid_diploids.tsv from the strain QC tables.

Groups (strain names, as in metadata.txt):
  rmuc_core           kept R. mucilaginosa strains minus the high-het (hybrid) diploids
  rmuc_core_outgroup  rmuc_core + haploid R. frigidialcoholis and R. aff. mucilaginosa (tree rooting)
  rmuc_with_hybrids   all kept R. mucilaginosa strains (rmuc_core + hybrid diploids)
  hybrid_diploids     kept diploids with het rate >= 0.1 (see hybrid_check.CM179498.tsv)
The pipeline builds `all` itself from every genotyped strain.

Usage: make_population_sets.py   (run from the project root)
"""
import csv
qc = list(csv.DictReader(open("results/variant_qc/strain_qc.tsv"), delimiter="\t"))
hc = {r["sample"]: r for r in csv.DictReader(open("results/variant_qc/hybrid_check.CM179498.tsv"), delimiter="\t")}
kept = [r for r in qc if r["decision"] == "keep"]
hyb = [r for r in kept if r["called_ploidy"] == "2" and float(r["het_rate"]) >= 0.1]
hyb_names = {r["strain"] for r in hyb}
core = [r["strain"] for r in kept if r["strain"] not in hyb_names]
outg = [r["strain"] for r in qc if r["called_ploidy"] == "1" and r["species"] in ("R. frigidialcoholis", "R. aff. mucilaginosa")]
groups = {
    "rmuc_core": sorted(core),
    "rmuc_core_outgroup": sorted(core + outg),
    "rmuc_with_hybrids": sorted(r["strain"] for r in kept),
    "hybrid_diploids": sorted(hyb_names),
}
with open("population_sets.yaml", "w") as o:
    o.write("# Generated by scripts/variant_qc/make_population_sets.py from\n"
            "# results/variant_qc/strain_qc.tsv and hybrid_check.CM179498.tsv. Edit the script, not this file.\n"
            "# Excluded strains and reasons: results/variant_qc/excluded_strains.tsv.\n"
            "# Hybrid diploids (kept out of rmuc_core): results/variant_qc/hybrid_diploids.tsv.\n"
            "# 'all' (every genotyped strain) is built by the pipeline and is not listed here.\n"
            "# Ploidy comes from ploidy_overrides.csv, not from this file. 2026-10-03:\n"
            "# DBVPG_3239, DBVPG_6094 and TFCN_25-332D-2 changed diploid -> haploid\n"
            "# (docs/ploidy_assessment_2026-10-03.md). They stay in rmuc_core.\n"
            "Populations:\n")
    for g, s in groups.items():
        o.write(f"  # {len(s)} strains\n  {g}:\n" + "".join(f"    - {x}\n" for x in s))
with open("results/variant_qc/hybrid_diploids.tsv", "w") as o:
    o.write("strain\tsubgroup\thet_rate\thet_sites_CM179498\talt_absent_in_haploids\talt_major_in_frig\talt_major_in_affmuc\n")
    for r in sorted(hyb, key=lambda r: r["strain"]):
        h = hc[r["vcf_sample"]]
        sub = "affmuc-like" if float(h["affmuc_alt>0.5"]) > 0.85 else "other"
        o.write(f"{r['strain']}\t{sub}\t{r['het_rate']}\t{h['het']}\t{h['muc_hap_alt=0']}\t{h['frig_alt>0.5']}\t{h['affmuc_alt>0.5']}\n")
for g, s in groups.items():
    print(g, len(s))
