#!/usr/bin/env python3
"""Write population_sets.yaml (bash-pipeline format: top-level `Populations:`)
and results/variant_qc/hybrid_diploids.tsv from the strain QC tables.

Groups (strain names, as in metadata.txt):
  rmuc_core           kept R. mucilaginosa strains minus the high-het (hybrid) diploids
  rmuc_core_outgroup  rmuc_core + haploid R. frigidialcoholis and R. aff. mucilaginosa (tree rooting)
  rmuc_with_hybrids   all kept R. mucilaginosa strains (rmuc_core + hybrid diploids)
  hybrid_diploids     kept diploids with het rate >= 0.1 (see hybrid_check.CM179498.tsv)
The pipeline builds `all` itself from every genotyped strain.
No phenotype-linked group is built here (user decision 2026-10-04). Strains are
dropped for association work in the phenotype project. This script still writes
results/variant_qc/rmuc_pheno_exclusions.tsv as a reference: rmuc_core strains
that have no phenotype row, a conflicting phenotype-table species, or an
identity concern.

Usage: make_population_sets.py   (run from the project root)
"""
import csv
qc = list(csv.DictReader(open("results/variant_qc/strain_qc.tsv"), delimiter="\t"))
hc = {r["sample"]: r for r in csv.DictReader(open("results/variant_qc/hybrid_check.CM179498.tsv"), delimiter="\t")}
# Strains dropped only for missing metadata.txt rows, added back after review
# (docs/ploidy_assessment_2026-10-03.md):
#   NRRL_Y-2510: R. mucilaginosa (phenotype table and its own reference genome
#   project); haploid by GATK, nQuire and het/Mb (56); 2.4% low-quality GTs.
INCLUDE_NO_METADATA = {"NRRL_Y-2510"}
# Libraries sequenced under another name and merged into one strain CRAM
# (scripts/merge_strain_crams.sh; docs/sample_id_fixes_2026-10-03.md). The old
# names no longer have a CRAM and must not appear in any group.
MERGED_INTO = {
    "TFCN_BY120-C1": "TFCN_25-0-2E333-9",   # 9003_002, plate position BY120-C1
    "TFCN_BY120-C7": "TFCN_25-0-2E333-9",   # 9003_028, plate position BY120-C7
    "CCFEE_5036": "DBVPG_5227",             # same isolate, two collection numbers
}
qc = [r for r in qc if r["strain"] not in MERGED_INTO]
for r in qc:
    if r["strain"] in INCLUDE_NO_METADATA:
        assert r["reasons"] == "no_metadata", (r["strain"], r["reasons"])
        r["decision"], r["reasons"] = "keep", "no_metadata_reviewed"
kept = [r for r in qc if r["decision"] == "keep"]
hyb = [r for r in kept if r["called_ploidy"] == "2" and float(r["het_rate"]) >= 0.1]
hyb_names = {r["strain"] for r in hyb}
core = [r["strain"] for r in kept if r["strain"] not in hyb_names]
outg = [r["strain"] for r in qc if r["called_ploidy"] == "1" and r["species"] in ("R. frigidialcoholis", "R. aff. mucilaginosa")]
# Reference only (no group): rmuc_core strains that need attention before
# association work. Reasons go to results/variant_qc/rmuc_pheno_exclusions.tsv.
PHENO_TABLE = "/bigdata/stajichlab/shared/projects/Rhodotorula/ExRhodotorula_Phenotypes/strains.csv"
EXCLUDE_ASSOC = {"EXF_1695": "mixed reads: minor-allele read fraction peaks at 0.10 (22.5 mixed sites/1000); possible mixed culture"}
ph = {r["STRAIN"]: r["ASSIGNEDSPECIES"] for r in csv.DictReader(open(PHENO_TABLE))}
pheno, pheno_excl = [], []
for x in sorted(core):
    if x not in ph:
        pheno_excl.append((x, "no phenotype row"))
    elif ph[x] != "Rhodotorula mucilaginosa":
        pheno_excl.append((x, f"phenotype table species is {ph[x]}; genotype is R. mucilaginosa: verify culture identity"))
    elif x in EXCLUDE_ASSOC:
        pheno_excl.append((x, EXCLUDE_ASSOC[x]))
    else:
        pheno.append(x)
with open("results/variant_qc/rmuc_pheno_exclusions.tsv", "w") as o:
    o.write("strain	reason\n")
    for x, why in pheno_excl:
        o.write(f"{x}\t{why}\n")
groups = {
    "rmuc_core": sorted(core),
    "rmuc_core_outgroup": sorted(core + outg),
    "rmuc_with_hybrids": sorted(r["strain"] for r in kept),
    "hybrid_diploids": sorted(hyb_names),
}
with open("population_sets.yaml", "w") as o:
    o.write("# Generated by scripts/variant_qc/make_population_sets.py from\n"
            "# results/variant_qc/strain_qc.tsv and hybrid_check.CM179498.tsv. Edit the script, not this file.\n"
            "# Excluded strains and reasons: results/variant_qc/excluded_strains.tsv.\n"
            "# Hybrid diploids (kept out of rmuc_core): results/variant_qc/hybrid_diploids.tsv.\n"
            "# 'all' (every genotyped strain) is built by the pipeline and is not listed here.\n"
            "# Ploidy comes from ploidy_overrides.csv, not from this file. 2026-10-03:\n"
            "# DBVPG_3239, DBVPG_6094 and TFCN_25-332D-2 changed diploid -> haploid\n"
            "# (docs/ploidy_assessment_2026-10-03.md). They stay in rmuc_core.\n"
            "# NRRL_Y-2510 has no metadata.txt row but was added after review.\n"
            "# Merged strains: TFCN_BY120-C1/C7 -> TFCN_25-0-2E333-9; CCFEE_5036 -> DBVPG_5227.\n"
            "# Phenotype-link notes (no group): results/variant_qc/rmuc_pheno_exclusions.tsv.\n"
            "# Clonal lineages: results/variant_qc/divergence/clone_groups_1e-3.tsv.\n"
            "Populations:\n")
    for g, s in groups.items():
        o.write(f"  # {len(s)} strains\n  {g}:\n" + "".join(f"    - {x}\n" for x in s))
with open("results/variant_qc/hybrid_diploids.tsv", "w") as o:
    o.write("strain\tsubgroup\thet_rate\thet_sites_CM179498\talt_absent_in_haploids\talt_major_in_frig\talt_major_in_affmuc\n")
    for r in sorted(hyb, key=lambda r: r["strain"]):
        h = hc[r["vcf_sample"]]
        sub = "affmuc-like" if float(h["affmuc_alt>0.5"]) > 0.85 else "other"
        o.write(f"{r['strain']}\t{sub}\t{r['het_rate']}\t{h['het']}\t{h['muc_hap_alt=0']}\t{h['frig_alt>0.5']}\t{h['affmuc_alt>0.5']}\n")
for g, s in groups.items():
    print(g, len(s))
